apiVersion: v1
kind: Service
metadata:
  name: vault-example-ui
  labels:
    app.kubernetes.io/name: vault-example-ui
spec:
  selector:
    app.kubernetes.io/name: vault-example
    component: server
  publishNotReadyAddresses: true
  ports:
    - name: http
      port: 8080
      targetPort: 8200