---
apiVersion: v1
kind: Namespace
metadata:
  name: team-b

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-team-b
  namespace: team-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-team-b
  template:
    metadata:
      labels:
        app: jenkins-team-b
    spec:
      containers:
      - name: jenkins
        image: jenkins/jenkins
        env:
          - name: JAVA_OPTS
            value: -Djenkins.install.runSetupWizard=false
        ports:
        - name: http-port
          containerPort: 8080
        - name: jnlp-port
          containerPort: 50000
        volumeMounts:
          - name: jenkins-home
            mountPath: /var/jenkins_home
      volumes:
        - name: jenkins-home
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: team-b
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: jenkins-team-b

---

apiVersion: v1
kind: Service
metadata:
  name: jenkins-jnlp
  namespace: team-b
spec:
  type: ClusterIP
  ports:
    - port: 50000
      targetPort: 50000
  selector:
    app: jenkins-team-b

---

# We need an ingress
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jenkins-team-b
  namespace: team-b
spec:
  rules:
  - host: jenkins-team-b.kubernetes.learn-devops.xyz
    http:
      paths:
      - path: /
        backend:
          serviceName: jenkins
          servicePort: 80
