apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: www-web-2
spec:
  dataSource:
    name: www-web-1-pv
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi