apiVersion: snapshot.storage.k8s.io/v1alpha1
kind: VolumeSnapshot
metadata:
  name: www-web-1-pv
spec:
  source:
    name: www-web-0
    kind: PersistentVolumeClaim

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: www-web-1
  labels:
    type: homefolder
spec:
  dataSource:
    name: www-web-1-pv
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi