apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grafana
  namespace: monitoring
spec:
  rules:
  - host: grafana.kubernetes.learn-devops.xyz
    http:
      paths:
      - path: /
        backend:
          serviceName: grafana
          servicePort: 80
